import "./globals.css";

export const metadata = {
  title: "Web tutorials", // 탭에 표시되는 제목
  description: "Generated by 감만정", // 메타 태그에 표시되는 설명
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
          <li><a href="/read/1">Html</a></li>
          <li><a href="/read/2">Css</a></li>
        </ol>
        {children}
        <ul>
          <li><a href="create">Create</a></li>
          <li><a href="update/1">Update</a></li>
          <li><input type="button" value="delete"></input></li>
        </ul>
      </body>
    </html>
  );
}
